version: '3.7'
services:
  cloudBroker:
    image: cloud_broker
    container_name: cloud_broker
    build: 
      "./Cloud/Broker"
  cloudClient:
    image: cloud_client
    container_name: cloud_client
    build: 
      "./Cloud/cloudClient"
  cloudPublisher:
    image: cloud_publisher
    container_name: cloud_publisher
    build: 
      "./Cloud/cloudPublisher"
  cloudServer:
    image: cloud_server
    container_name: cloud_server
    build: 
      "./Cloud/cloudServer"
  edgeBroker:
    image: edge_broker
    container_name: edge_broker
    build: 
      "./Edge/Broker"
    ports:
      - "3005:3005"
      # - "4883:4883"
    # expose:
    #   - 3005
      # - 27017
    #   - 4883
    # expose:
    # - "3005"
  edgeDataManager:
    image: edge_data_manager
    container_name: edge_data_manager
    build: 
      "./Edge/DataManager"
  edgeIoTDevSim:
    image: edge_iot_dev_sim
    container_name: edge_iot_dev_sim
    build: 
      "./Edge/IoTDevSim"
    # expose:
      # - 4883
      # - 8080
      # - 8081
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim2:
    image: edge_iot_dev_sim_2
    container_name: edge_iot_dev_sim_2
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim3:
    image: edge_iot_dev_sim_3
    container_name: edge_iot_dev_sim_3
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim4:
    image: edge_iot_dev_sim_4
    container_name: edge_iot_dev_sim_4
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim5:
    image: edge_iot_dev_sim_5
    container_name: edge_iot_dev_sim_5
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300

  edgeIoTDevSim6:
    image: edge_iot_dev_sim_6
    container_name: edge_iot_dev_sim_6
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim7:
    image: edge_iot_dev_sim_7
    container_name: edge_iot_dev_sim_7
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim8:
    image: edge_iot_dev_sim_8
    container_name: edge_iot_dev_sim_8
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim9:
    image: edge_iot_dev_sim_9
    container_name: edge_iot_dev_sim_9
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
  edgeIoTDevSim10:
    image: edge_iot_dev_sim_10
    container_name: edge_iot_dev_sim_10
    build: 
      "./Edge/IoTDevSim"
    mem_limit: 1gb
    blkio_config:
      weight: 300
      
  edgeSubscriber:
    image: edge_subscriber
    container_name: edge_subscriber
    build: 
      "./Edge/subscriber"
  mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"


volumes:
  mongo-db: