version: '3.7'
services:
  # cloudBroker:
  #   image: cloud_broker
  #   container_name: cloud_broker
  #   build: 
  #     "./Cloud/Broker"
  # cloudClient:
  #   image: cloud_client
  #   container_name: cloud_client
  #   build: 
  #     "./Cloud/cloudClient"
  # cloudPublisher:
  #   image: cloud_publisher
  #   container_name: cloud_publisher
  #   build: 
  #     "./Cloud/cloudPublisher"
  # cloudServer:
  #   image: cloud_server
  #   container_name: cloud_server
  #   build: 
  #     "./Cloud/cloudServer"
  edgeBroker:
    image: edge_broker
    container_name: edge_broker
    build: 
      "./Edge/Broker"
    ports:
      - "3005:3005"
      # - "4883:4883"
    # expose:
    #   - 3005
      # - 27017
    #   - 4883
    # expose:
    # - "3005"
  # edgeDataManager:
  #   image: edge_data_manager
  #   container_name: edge_data_manager
  #   build: 
  #     "./Edge/DataManager"
  edgeIoTDevSim:
    image: edge_iot_dev_sim
    container_name: edge_iot_dev_sim
    build: 
      "./Edge/IoTDevSim"
    expose:
      - 4883
      - 8080
      - 8081
    mem_limit: 1gb
    blkio_config:
      weight: 300
      # weight_device:
        # - path: /dev/sda
          # weight: 400
      # device_read_bps:
        # - path: /dev/sdb
          # rate: '12mb'
      # device_read_iops:
        # - path: /dev/sdb
          # rate: 120
      # device_write_bps:
        # - path: /dev/sdb
          # rate: '1024k'
      # device_write_iops:
        # - path: /dev/sdb
          # rate: 30
    # mem_reservation: "512m"
    # cpus: "1"
    # cpuset: "2"
  # edgeIoTSmartDev:
  #   image: edge_iot_smart_dev
  #   container_name: edge_iot_smart_dev
  #   build: 
  #     "./Edge/IoTSmartDev"
  #   mem_limit: 300m
    # mem_reservation: "512m"
    # cpus: "1"
    # cpuset: "2"
  edgeSubscriber:
    image: edge_subscriber
    container_name: edge_subscriber
    build: 
      "./Edge/subscriber"
  mongodb-myapp:
      image: mongo:latest
      ports:
        - "27017:27017"


volumes:
  mongo-db: